### ISSUE TITLE
no icons on items

### ISSUE THREAD

**Issue by valenvaio** [rodel77/MarketPlace-Web#6]
https://www.fairserver.ru/market/
https://rodeldev.xyz/marketplace/

**Comment by rodel77** [comment]
That issue is known, I have been working for a long time in a new web version (in branch 2.0)

**Comment by valenvaio** [comment]
Can I get a betta for testing?

**Comment by rodel77** [comment]
Well, the [2.0 branch](https://github.com/rodel77/MarketPlace-Web/tree/2.0) has relatively "incomplete" docs about how to setup the page, but I don't really recommend you to do it on production since I am introducing the purchase-through-web system, is not finished and is not still not stable (also you would need the plugin's updated version)

If I take to much time on 2.0, probably I will try to release another version of 1.0 just fixing the icons
